[workspace]
members = [
    "yuca",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
rustix = { version = "0.38.37", features = ["fs"] }
tokio = { version = "1.42.0", features = ["net", "macros", "rt"] }
