[package]
name = "yuca"
version = "0.1.0"
edition = "2021"

[dependencies]
rustix = { version = "0.38.37", features = ["fs"] }
strum = { version = "0.26.3", features = ["derive"] }
thiserror = "1.0.64"

[dev-dependencies]
googletest = "0.12.0"
